#!/bin/bash

set -e

#!/bin/bash

set -e

WORKSPACE=$(pwd)

cmake --build $WORKSPACE/build

# gcc -shared -Iinclude -std=c99 -pedantic -ggdb3 -O0 -fPIC \
#   -ftree-vectorize -msse2 -mfpmath=sse \
#   -Wall -Wextra -Werror -o libexec/libmymath.so \
#   src/avg.c \
#   src/cbrt.c \
#   src/cosh.c \
#   src/cub.c \
#   src/entropy.c \
#   src/exp.c \
#   src/fabs.c \
#   src/floor.c \
#   src/gcd.c \
#   src/ln.c \
#   src/log.c \
#   src/log2.c \
#   src/log10.c \
#   src/logbase.c \
#   src/matrix.c \
#   src/max.c \
#   src/median.c \
#   src/min.c \
#   src/mode.c \
#   src/pow.c \
#   src/prime.c \
#   src/relu.c \
#   src/rng.c \
#   src/root.c \
#   src/sem.c \
#   src/sigmoid.c \
#   src/sinh.c \
#   src/skew.c \
#   src/sqr.c \
#   src/sqrt.c \
#   src/stddev.c \
#   src/tanh.c \
#   src/variance.c \
#   src/vector.c

# gcc -Iinclude -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -ftree-vectorize -msse2 -mfpmath=sse \
#   -Wall -Wextra -Werror -o bin/main \
#   src/main.c -lmymath

# gcc -Iinclude -Itest/include -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -Wall -o bin/cbrt_test \
#   test/lib/wrapper.c \
#   test/cbrt_test.c -lcmocka -lmymath

# gcc -Iinclude -Itest/include -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -Wall -o bin/cub_test \
#   test/lib/wrapper.c \
#   test/cub_test.c -lcmocka -lmymath

# gcc -Iinclude -Itest/include -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -Wall -o bin/exp_test \
#   test/lib/wrapper.c \
#   test/exp_test.c -lcmocka -lmymath -lm

# gcc -Iinclude -Itest/include -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -ftree-vectorize -msse2 -mfpmath=sse \
#   -Wall -o bin/fabs_test \
#   test/lib/wrapper.c \
#   test/fabs_test.c -lcmocka -lmymath

# gcc -Iinclude -Itest/include -Llibexec -std=c99 -pedantic -ggdb3 -O0 \
#   -Wall -o bin/floor_test \
#   test/lib/wrapper.c \
#   test/floor_test.c -lcmocka -lmymath


# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/exp_test \
#   test/benchmark/exp_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/cbrt_test \
#   test/benchmark/cbrt_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/cosh_test \
#   test/benchmark/cosh_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/cub_test \
#   test/benchmark/cub_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/fabs_test \
#   test/benchmark/fabs_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/floor_test \
#   test/benchmark/floor_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/pow_test \
#   test/benchmark/pow_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/sinh_test \
#   test/benchmark/sinh_test.cpp -lbenchmark -lpthread -lm -lmymath

# g++ -Iinclude -Itest/include -Llibexec -O3 \
#   -Wall -o bin/benchmark/tanh_test \
#   test/benchmark/tanh_test.cpp -lbenchmark -lpthread -lm -lmymath
